# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30305b81299b45952ad6cd42d3704c868c6919bda161e0725f602b881e4b41132db7c23a7a99d7786c5eb7ead87d44df55a7bb6270fdf30e53e332273bd239a

test:
  secret_key_base: d33e39344287043ced64d49c8fd6ae83645735673329cd93789b312e38ff0b6f8727571928fbce695811d70192c11ef4a329846ef7b0908522630a9a10a1c0fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
